// build.rs — SPEC-DERIVED anchor inventory generator.
//
// SPEC-DERIVED-§15.2 (Architecture.md), SPEC-DERIVED-§16 (CellTaxonomy.md):
// every `SPEC-DERIVED-§N.N` marker in the corpus must have a live AnchorNode.
// This build script walks `src/` and `tests/`, harvests every marker of the
// form `SPEC-DERIVED-§<section> (<Doc.md>)`, and emits a static inventory
// that the Bootstrap Operator registers with SpecAnchorCell in Phase B3a.6.
//
// Zero dependencies; std only.

use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    if let Ok(rd) = fs::read_dir(dir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.is_dir() {
                walk(&p, out);
            } else if p.extension().map(|x| x == "rs").unwrap_or(false) {
                out.push(p);
            }
        }
    }
}

fn main() {
    println!("cargo:rerun-if-changed=src");
    println!("cargo:rerun-if-changed=tests");
    println!("cargo:rerun-if-changed=build.rs");

    let mut files = Vec::new();
    walk(Path::new("src"), &mut files);
    walk(Path::new("tests"), &mut files);
    files.sort();

    // (doc, section, artifact_path, line)
    let mut anchors: Vec<(String, String, String, usize)> = Vec::new();

    for f in &files {
        let text = match fs::read_to_string(f) {
            Ok(t) => t,
            Err(_) => continue,
        };
        for (lineno, line) in text.lines().enumerate() {
            let mut rest = line;
            while let Some(idx) = rest.find("SPEC-DERIVED-\u{00a7}") {
                let after = &rest[idx + "SPEC-DERIVED-\u{00a7}".len()..];
                // section token: up to whitespace or '(' or end
                let sec_end = after
                    .find(|c: char| c.is_whitespace() || c == '(' || c == ',' || c == ')')
                    .unwrap_or(after.len());
                let section = after[..sec_end].trim_end_matches('.').to_string();
                // optional "(Doc.md)" provenance
                let doc = after[sec_end..]
                    .trim_start()
                    .strip_prefix('(')
                    .and_then(|s| s.split(')').next())
                    .map(|s| s.trim().to_string())
                    .unwrap_or_else(|| "Architecture.md".to_string());
                if !section.is_empty() {
                    anchors.push((
                        doc,
                        section,
                        f.to_string_lossy().replace('\\', "/"),
                        lineno + 1,
                    ));
                }
                rest = &after[sec_end..];
            }
        }
    }

    anchors.sort();
    anchors.dedup();

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("spec_anchor_inventory.rs");
    let mut w = fs::File::create(&dest).expect("create inventory");
    writeln!(
        w,
        "/// Auto-generated by build.rs. (doc, section, artifact_path, line)."
    )
    .unwrap();
    writeln!(
        w,
        "pub static SPEC_ANCHOR_INVENTORY: &[(&str, &str, &str, u32)] = &["
    )
    .unwrap();
    for (doc, sec, path, line) in &anchors {
        writeln!(
            w,
            "    ({:?}, {:?}, {:?}, {}),",
            doc, sec, format!("{}:{}", path, line), line
        )
        .unwrap();
    }
    writeln!(w, "];").unwrap();
}
